# Generated by Django 6.0.1 on 2026-01-14 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallSourceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="The number in E.164 format used to initiate the missed call.",
                        max_length=32,
                        unique=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to temporarily remove the number from the pool.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Internal name to identify this specific line (e.g., 'Twilio US 01').",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "call source number",
                "verbose_name_plural": "call source numbers",
            },
        ),
        migrations.CreateModel(
            name="MissedCallVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="user phone number"
                    ),
                ),
                (
                    "app_signature",
                    models.CharField(
                        db_index=True,
                        help_text="Unique hash identifying the mobile application binary.",
                        max_length=255,
                        verbose_name="application signature",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "expected_caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="rest_framework_missedcall.callsourcenumber",
                        verbose_name="expected caller",
                    ),
                ),
            ],
            options={
                "verbose_name": "missed call verification",
                "verbose_name_plural": "missed call verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_phone", "is_verified"],
                        name="rest_framew_user_ph_8bb0d4_idx",
                    )
                ],
            },
        ),
    ]
